services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flustra-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
