services:
  mysql:
    image: mysql:8.0
    container_name: flustra-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_flustra-pricing
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:20
    container_name: flustra-node
    working_dir: /var/www/html
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html
      - node_modules_data:/var/www/html/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  app:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flustra-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
      - node_modules_data:/var/www/html/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: |
      sh -c "
      if [ ! -d '/var/www/html/vendor/composer' ]; then
        echo 'Installing PHP dependencies (Composer)...'
        composer install --no-interaction --optimize-autoloader
      fi
      exec php artisan serve --host=0.0.0.0 --port=8000
      "

volumes:
  vendor_data:
  node_modules_data:
  db_data:
